language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - mercurial 

script:
  - hg --version
  - mvn verify -Pits -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
